my_string = "hello world"
c = my_string.count("h")
print(c)
c = my_string.startswith("h")
print(c)
c = my_string.endswith("h")
print(c)
c = my_string.index("h")
print(c)
c = my_string.find("h")
print(c)
c = my_string.replace("h" , "r")
print(c)
c = my_string.strip()
print(c)